#!/usr/bin/env python3

import urllib.request

def check_internet():
    try:
        urllib.request.urlopen('https://www.google.com', timeout=1)
        return True
    except urllib.error.URLError:
        return False

if check_internet():
    print("󰖩")
else:
    print("󱚼 ")
